### ISSUE TITLE
Comparison to InfluxDB.Net

### ISSUE THREAD

**Issue by pootzko** [AdysTech/InfluxDB.Client.Net#1]
Hi,

this is not really an "issue", more a question. What's the difference between your library and [InfluxDB.Net](https://github.com/ziyasal/InfluxDB.Net)? Why didn't you use/modify/update the existing one? Any insight would be great. 

Thank you. :)

**Comment by mvadu** [comment]
Well, when I heard about InfluxDB, they were already in 0.9x release, and it broke everything with 0.8x (from JSON to line protocol). That time the other project appeared to have been in hibernation. Since it was anyway a fresh start with new protocol, I started afresh, and used it as part of [Influxer](https://github.com/AdysTech/Influxer). Recently I moved it as a separate client library and published it. 

So to answer your question, Yes, I could have refactored existing one, but decided to start new as old was not compatible with Influx 0.9x.

**Comment by pootzko** [comment]
Ok, thanks for the info. :)
