### ISSUE TITLE
InfluxDataPoint fields cannot be different types.

### ISSUE THREAD

**Issue by scarfie** [AdysTech/InfluxDB.Client.Net#7]
There may be situations where we have multiple fields that have different data types. For example we may have a integer value for responseTime and a string value for requestId,

The current data structure does not support this, as the fields are a dictionary<string, T> where T is the specified type.

**Comment by mvadu** [comment]
@scarfie This is more by design. My idea was to have type safety, where multiple fields of single type T are contained in single `InfluxDataPoint<T>`. As you can see from [TestPostPointsAsync](https://github.com/AdysTech/InfluxDB.Client.Net/blob/4193d671d073c233cbdc67882840f7d413a8311c/AdysTech.InfluxDB.Client.Net.Test/InfluxDBClientTest.cs#L277) if you want to have an int and a string points in same measurement, you create multiple points (`InfluxDatapoint<string> and InfluxDatapoint<int>`) and set it to same measurement name. Then the `PostPointsAsync` combines them into single insert line protocol statement.
